blog_posts/urls.py
from django.urls import path
from . import views

app_name = 'blog_posts'

urlpatterns = [
    path('', views.posts_list, name="list"),
    path('<slug:slug>', views.post_page, name="page"),
    path('api/posts/', views.get_all_posts_json, name='get_all_posts_json'),
    path('api/posts/<int:post_id>/', views.get_post_by_id_json, name='get_post_by_id_json'),
]

eblog/eblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    # TokenVerifyView
)

# from users.views import RegisterView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('blog_posts/', include('blog_posts.urls')),
    path('api/sign-in/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/sign-up/', RegisterView.as_view(), name='register_name'),
    #  path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

eblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    # TokenVerifyView
)

from users.views import RegisterView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('blog_posts/', include('blog_posts.urls')),
    path('api/sign-in/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/sign-up/', RegisterView.as_view(), name='register_name'),
    #  path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

blog_posts/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    pass

blog_posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse, HttpResponse
from .models import Post

def posts_list(request):
    posts = Post.objects.all().order_by('date')
    return render(request, 'blog_posts/posts_list.html', {'posts': posts})


def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'blog_posts/post_page.html', {'post': post})


def get_all_posts_json(request):
    if request.method == 'GET':
        posts = Post.objects.all()
        data = [
            {
                'id': post.id,
                'title': post.title,
                'body': post.body,
                'slug': post.slug,
                'date': post.date.isoformat(),
            }
            for post in posts
        ]
        return JsonResponse(data, safe=False)

def get_post_by_id_json(request, post_id):
    if request.method == 'GET':
        post = get_object_or_404(Post, id=post_id)
        data = {
            'id': post.id,
            'title': post.title,
            'body': post.body,
            'slug': post.slug,
            'date': post.date.isoformat(),
        }
        return JsonResponse(data)

eblog/users/views.py
from rest_framework import status, generics
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from django.contrib.auth import get_user_model
from rest_framework.views import APIView
from rest_framework import serializers

from rest_framework_simplejwt.tokens import RefreshToken

from eblog.users.serializers import RegisterSerializer

User = get_user_model()

class RegisterView(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = RegisterSerializer

    def perform_create(self, serializer):
        user = serializer.save()
        refresh = RefreshToken.for_user(user)
        return Response({
            'refresh': str(refresh),
            'access': str(refresh.access_token)
        }, status=status.HTTP_201_CREATED)

eblog/views.py
# from django.http import HttpResponse
from django.shortcuts import render
def homepage(request):
    # return HttpResponse("How to choose and how to cook potatoes: tips from the chef!")
    return render(request, 'home.html')


def about(request):
    # return HttpResponse("About Page")
    return render(request, 'about.html')

users/views.py
from rest_framework import status, generics
from rest_framework.response import Response
from django.contrib.auth import get_user_model

from rest_framework_simplejwt.tokens import RefreshToken

from users.serializers import RegisterSerializer

User = get_user_model()

class RegisterView(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = RegisterSerializer

    def perform_create(self, serializer):
        user = serializer.save()
        refresh = RefreshToken.for_user(user)
        return Response({
            'refresh': str(refresh),
            'access': str(refresh.access_token)
        }, status=status.HTTP_201_CREATED)

blog_posts/templates/blog_posts/post_page.html
{% extends 'layout.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <section>
      <h1>{{ post.title }}</h1>
      <p>{{ post.date }}</p>
      <p>{{ post.body }}</p>
    </section>
{% endblock %}

blog_posts/templates/blog_posts/posts_list.html
{% extends 'layout.html' %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
    <section>
        <h1>Posts</h1>
        {% for post in posts %}
            <article class="post">
                <h2>
                    <a href="{% url 'blog_posts:page' slug=post.slug %}">
                        {{ post.title }}
                    </a>
                </h2>
                <p>{{ post.date }}</p>
                <p>{{ post.body }}</p>
            </article>
        {% endfor %}
    </section>
{% endblock %}

eblog/templates/about.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>About</title>
    <script src="{% static 'js/main.js' %}" defer></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <h1>About</h1>
    <p>Check out my <a href="/">Home</a> page.</p>
</body>
</html>

templates/about.html
{% extends 'layout.html' %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>Darya's potato blog</p>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Home</h1>
    <p>How to choose and how to cook potatoes: tips from the chef!</p>
{% endblock %}

templates/layout.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
      {% block title %}
        Django App
      {% endblock %}
    </title>
    <script src="{% static 'js/main.js' %}" defer></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <nav>
    <a href="/">
        <span role="img" aria-label="Home">🏠</span>
    </a> |
    <a href="{% url 'blog_posts:list' %}">
        <span role="img" aria-label="Home">📰</span>
    </a> |
    <a href="/about">
        <span role="img" aria-label="Home">❓</span>
    </a>
  </nav>
  <main>
    {% block content %}
        Django Content
    {% endblock %}
  </main>
</body>
</html>